// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxUfn_JunRjnKhhU9LjjGNIiLvqTyho0',
    appId: '1:755517485907:web:84f92899a83aafe3af27a6',
    messagingSenderId: '755517485907',
    projectId: 'test1-9f7dd',
    authDomain: 'test1-9f7dd.firebaseapp.com',
    storageBucket: 'test1-9f7dd.appspot.com',
    measurementId: 'G-HEC3Q50YJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7MNlQFuZPH3uePDLThqo59IJmhQk8h0A',
    appId: '1:755517485907:android:f254413a25e486ebaf27a6',
    messagingSenderId: '755517485907',
    projectId: 'test1-9f7dd',
    storageBucket: 'test1-9f7dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS0k_NsV6tXxSWNvzAFckKzx0QnbfHT8Q',
    appId: '1:755517485907:ios:ca1aa3668a0856deaf27a6',
    messagingSenderId: '755517485907',
    projectId: 'test1-9f7dd',
    storageBucket: 'test1-9f7dd.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS0k_NsV6tXxSWNvzAFckKzx0QnbfHT8Q',
    appId: '1:755517485907:ios:e5d38dedf56efa8daf27a6',
    messagingSenderId: '755517485907',
    projectId: 'test1-9f7dd',
    storageBucket: 'test1-9f7dd.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
